import { LanternConfig } from '../types';

export const LANTERN_CONFIG: LanternConfig[] = [
    { id: 'far-left', positionClass: 'left-[5%] -top-10', animationClass: 'animate-[sway-slow_7s_infinite_ease-in-out]', lineHeight: 'h-40', variant: 'simple', sizeClass: 'w-16 text-gold-antique', glowColor: '#F4A460', parallaxSpeed: 0.15, mobileHidden: true, zIndex: 0 },
    { id: 'mid-left', positionClass: 'left-[12%] -top-10', animationClass: 'animate-[sway_6s_infinite_ease-in-out_1s]', lineHeight: 'h-64', variant: 'royal', sizeClass: 'w-24 text-gold-lantern', glowColor: '#FFD700', parallaxSpeed: 0.25, mobileHidden: true, zIndex: 10, gradient: true },
    { id: 'close-left', positionClass: 'left-2 md:left-[2%] -top-16 md:-top-20', animationClass: 'animate-[sway-fast_8s_infinite_ease-in-out_0.5s] group-hover:scale-105 transition-transform duration-700', lineHeight: 'h-48 md:h-96', variant: 'royal', sizeClass: 'w-20 md:w-40 text-gold-bright drop-shadow-[0_0_30px_rgba(212,175,55,0.4)] opacity-[0.45]', glowColor: '#FFD700', flickerIntensity: 'high', parallaxSpeed: 0.4, mobileHidden: false, zIndex: 20, gradient: true },
    { id: 'close-right', positionClass: 'right-2 md:right-[5%] -top-12 md:-top-10', animationClass: 'animate-[sway_7s_infinite_ease-in-out_2s] group-hover:scale-105 transition-transform duration-700', lineHeight: 'h-40 md:h-80', variant: 'geometric', sizeClass: 'w-16 md:w-36 text-gold-bright drop-shadow-[0_0_30px_rgba(212,175,55,0.4)] opacity-[0.4]', glowColor: '#F4A460', flickerIntensity: 'high', parallaxSpeed: 0.4, mobileHidden: false, zIndex: 20, gradient: true },
    { id: 'mid-right', positionClass: 'right-[15%] -top-10', animationClass: 'animate-[sway-slow_5s_infinite_ease-in-out_1.5s]', lineHeight: 'h-56', variant: 'royal', sizeClass: 'w-20 text-gold-antique', glowColor: '#FFD700', parallaxSpeed: 0.25, mobileHidden: true, zIndex: 10, gradient: true },
    { id: 'far-right', positionClass: 'right-[25%] -top-10', animationClass: 'animate-[sway_9s_infinite_ease-in-out_3s]', lineHeight: 'h-48', variant: 'simple', sizeClass: 'w-14 text-gold-antique', glowColor: '#F4A460', parallaxSpeed: 0.15, mobileHidden: true, zIndex: 0 },
];
