-- FULL MIGRATION SCRIPT (206 records)
-- Run this in Supabase SQL Editor

BEGIN;

-- 1. Clear existing data
TRUNCATE TABLE public.spots RESTART IDENTITY;

-- 2. Insert all spots
INSERT INTO public.spots (
  location_id, 
  venue_name, 
  city, 
  primary_area, 
  locality, 
  landmark, 
  zone, 
  latitude, 
  longitude, 
  venue_type, 
  food_type, 
  timing, 
  availability, 
  price, 
  notes,
  features, 
  target_audience, 
  phones, 
  contact_persons
) VALUES 
(
      1,
      'Hotel Topper',
      'Chennai',
      'Adyar',
      NULL,
      'Near Adyar bus depot, Masjid Campus',
      NULL,
      13.0012,
      80.2565,
      'Hotel',
      'Paid',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      2,
      'Hotel Liberty',
      'Chennai',
      'Guindy',
      NULL,
      NULL,
      NULL,
      13.0067,
      80.2206,
      'Hotel',
      'Paid',
      '{"start":"03:30","end":"04:30"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      ARRAY['044-22317400','044-22330719']::text[],
      NULL
    ),
(
      3,
      'Alandur Masjid (Masjid-E-Ahle Hadees)',
      'Chennai',
      'Alandur',
      'Alandur',
      'Near Aone Stationery Shop',
      NULL,
      12.9975,
      80.2006,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:30"}'::jsonb,
      'Last 5 odd nights (21, 23, 25, 27, 29)',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      4,
      'AKR Trust (AKR Steel)',
      'Chennai',
      'Guindy',
      'Guindy Market',
      'Near Gandhi Statue',
      NULL,
      NULL,
      NULL,
      'Trust',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5,
      'Gandhi Market Masjid',
      'Chennai',
      'Guindy',
      'Guindy Market',
      NULL,
      NULL,
      13.0102,
      80.2157,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Last 5 odd nights (21, 23, 25, 27, 29)',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      6,
      'Private Arrangement',
      'Chennai',
      'Kodambakkam',
      NULL,
      'Near Kodambakkam Bridge & Hotel Udopi',
      NULL,
      NULL,
      NULL,
      'Private Arrangement',
      'Paid',
      NULL,
      NULL,
      '₹1000/month',
      'Advance registration required',
      ARRAY['Paid','PreBookingRequired']::text[],
      NULL,
      ARRAY['9176807107']::text[],
      ARRAY['Mohamed Meeran Sahib']::text[]
    ),
(
      7,
      'FB Masjid',
      'Chennai',
      'Nandanam',
      NULL,
      'Opposite YMCA Ground',
      NULL,
      13.0628,
      80.2643,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      'Register name during Asar prayer',
      ARRAY['Free','Masjid','PreBookingRequired']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      9,
      'Hotel Fanar',
      'Chennai',
      'Peryamet',
      NULL,
      'Opposite Peryamet Masjid',
      NULL,
      13.0827,
      80.2707,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      'Other nearby hotels may open during Sahar time',
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      10,
      'Dasthgir Sahib Jama Masjid',
      'Chennai',
      'Saidapet',
      NULL,
      NULL,
      NULL,
      13.0124,
      80.2316,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      ARRAY['9003231307']::text[],
      ARRAY['Br. Sameeruddin']::text[]
    ),
(
      11,
      'Hotel K.R. Palace',
      'Chennai',
      'Saidapet',
      NULL,
      'Near Saidapet Railway Station',
      NULL,
      NULL,
      NULL,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      12,
      'Saidapet Masjid',
      'Chennai',
      'Saidapet',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      13,
      'Hotel Grand',
      'Chennai',
      'T. Nagar',
      NULL,
      NULL,
      NULL,
      13.0475,
      80.2506,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      14,
      'Hotel Virudhunagar (T. Nagar branch)',
      'Chennai',
      'T. Nagar',
      NULL,
      '77, G.N. Chetty Road, Panagal Park',
      NULL,
      13.0418,
      80.2341,
      'Hotel',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['044-42122769']::text[],
      NULL
    ),
(
      15,
      'Masjid-e-Hidayath',
      'Chennai',
      'T. Nagar',
      NULL,
      'South Boag Road',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      16,
      'Masjid-e-Allah',
      'Chennai',
      'Taramani',
      NULL,
      'Near TCS, Vijayan Nagar, 100 Feet Road',
      NULL,
      12.9929,
      80.2461,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      17,
      'Taramani Masjid',
      'Chennai',
      'Taramani',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      18,
      'Thandeeswara Nagar Masjid',
      'Chennai',
      'Velachery',
      'Thandeeswara Nagar',
      'Near IIT Gate (West)',
      NULL,
      12.9805,
      80.2254,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      19,
      'Maduvinkarai Masjid',
      'Chennai',
      'Velachery',
      NULL,
      NULL,
      NULL,
      13.0034,
      80.2185,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      20,
      'Hotel Buhari (Velachery branch)',
      'Chennai',
      'Velachery',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      21,
      'Hotel Sagar',
      'Chennai',
      'Triplicane',
      NULL,
      NULL,
      NULL,
      13.064,
      80.2806,
      'Hotel',
      'Paid',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      22,
      'Hotel Bilal',
      'Chennai',
      'Triplicane',
      'Big Mosque Road',
      NULL,
      NULL,
      13.0638,
      80.2722,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      23,
      'Masjid-e-Mamoor',
      'Chennai',
      'George Town',
      'Angappa Naicken St',
      NULL,
      NULL,
      13.0944,
      80.29,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      24,
      'Hotel Crescent (Nungambakkam branch)',
      'Chennai',
      'Nungambakkam',
      NULL,
      NULL,
      NULL,
      13.0592,
      80.24,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      25,
      'Hotel Barkath',
      'Chennai',
      'Royapettah',
      NULL,
      NULL,
      NULL,
      13.0539,
      80.2641,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      26,
      'Hotel Buhari',
      'Chennai',
      'Mount Road',
      NULL,
      NULL,
      NULL,
      13.0638,
      80.2652,
      'Hotel',
      'Paid',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      27,
      'Big Mosque',
      'Chennai',
      'Washermanpet',
      NULL,
      NULL,
      NULL,
      13.1072,
      80.2867,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      28,
      'Masjid-e-Khadeejathul Kubra',
      'Chennai',
      'Anna Nagar',
      NULL,
      NULL,
      NULL,
      13.0545,
      80.2422,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      29,
      'Masjid-e-Abubakar',
      'Chennai',
      'Perambur',
      NULL,
      NULL,
      NULL,
      13.116,
      80.2317,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      30,
      'Hotel Crescent',
      'Chennai',
      'Egmore',
      NULL,
      'Opposite Egmore Railway Station',
      NULL,
      13.0788,
      80.2565,
      'Hotel',
      'Paid',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      31,
      'Masjid-e-Mohideen',
      'Chennai',
      'Purasaiwalkam',
      NULL,
      'Close to Abirami Mega Mall',
      NULL,
      13.0895,
      80.252,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Last 10 nights',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      32,
      'Rahmath Hotel',
      'Chennai',
      'Vepery',
      NULL,
      'Near Vepery High Road',
      NULL,
      13.0844,
      80.2721,
      'Hotel',
      'Paid',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      33,
      'Al-Habeeb Restaurant',
      'Chennai',
      'Teynampet',
      NULL,
      'Near SIET College',
      NULL,
      13.0444,
      80.2516,
      'Restaurant',
      'Paid',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      34,
      'Big Mosque Royapuram',
      'Chennai',
      'Royapuram',
      NULL,
      NULL,
      NULL,
      13.1083,
      80.2942,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      35,
      'Masjid-e-Noor (Kottivakkam)',
      'Chennai',
      'Thiruvanmiyur',
      'Kottivakkam',
      'Near ECR Road',
      NULL,
      12.9753,
      80.2586,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Last 10 nights',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      36,
      'Masjid Al-Falah',
      'Chennai',
      'Perungudi',
      NULL,
      'Close to Toll Plaza',
      NULL,
      12.9644,
      80.2447,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      37,
      'Masjid-e-Quba',
      'Chennai',
      'Aminjikarai',
      NULL,
      'Behind Skywalk Mall',
      NULL,
      13.0739,
      80.2258,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      38,
      'Zam Zam Restaurant',
      'Chennai',
      'Arumbakkam',
      NULL,
      'Near CMBT Bus Stand',
      NULL,
      13.064,
      80.2199,
      'Restaurant',
      'Paid',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      39,
      'Masjid-e-Taqwa',
      'Chennai',
      'Vadapalani',
      NULL,
      'Opposite Vijaya Mall',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      40,
      'Masjid-e-Bilal',
      'Chennai',
      'Pallavaram',
      NULL,
      'Near Railway Station',
      NULL,
      12.9497,
      80.1417,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Last 10 nights',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      41,
      'Hotel Mubarak',
      'Chennai',
      'Chromepet',
      NULL,
      'Near MIT Flyover',
      NULL,
      NULL,
      NULL,
      'Hotel',
      'Paid',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      42,
      'Masjid-e-Salam',
      'Chennai',
      'Koyambedu',
      NULL,
      'Near Flower Market',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      43,
      'Masjid-e-Sofia',
      'Chennai',
      'Vyasarpadi',
      NULL,
      'Near MKB Nagar',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Last 10 nights',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      44,
      'Masjid-e-Rahmaniya',
      'Chennai',
      'Manali',
      NULL,
      'Near Manali New Town Bus Stop',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      45,
      'Masjid-e-Madina',
      'Chennai',
      'Avadi',
      NULL,
      'Near Avadi Market',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      46,
      'Masjid-e-Fathima',
      'Chennai',
      'Mogappair',
      NULL,
      'Near Golden Flats',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Last 10 nights',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      47,
      'Masjid-e-Siddique',
      'Chennai',
      'Tiruvottiyur',
      NULL,
      'Near Railway Station',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      48,
      'Masjid-e-Nurul Islam',
      'Chennai',
      'Madhavaram',
      NULL,
      'Near Madhavaram Roundtana',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Masjid']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      49,
      'Masjid-e-Hameedia',
      'Chennai',
      'Shenoy Nagar',
      NULL,
      'Near Shenoy Nagar Metro Station',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Last 10 nights',
      NULL,
      NULL,
      ARRAY['Free','Masjid','LimitedDays']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      50,
      'Hotel Virudhunagar (Meenambakkam branch)',
      'Chennai',
      'Meenambakkam',
      'Near Airport',
      'Near Chennai Airport',
      NULL,
      12.9882,
      80.1765,
      'Hotel',
      'Paid',
      '{"start":"02:30","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      NULL,
      '{}'::text[],
      NULL,
      NULL,
      NULL
    ),
(
      51,
      'Jummah Masjid (MGR Nagar)',
      'Chennai',
      'MGR Nagar',
      NULL,
      'MGR Nagar, Chennai 600078',
      NULL,
      13.045,
      80.1989,
      'Masjid',
      'Free',
      '{"start":"03:00"}'::jsonb,
      NULL,
      NULL,
      'Pre-booking window: 17:00–21:00',
      ARRAY['Free','Masjid','PreBookingRequired']::text[],
      NULL,
      NULL,
      ARRAY['S. Ayub Khan','S. Haja Mohideen','K. Ismail Dawoodi','M. Basheer Ahmed']::text[]
    ),
(
      52,
      'TNTJ Sehri – Omandur Hospital',
      'Chennai',
      'Egmore',
      'Omandur Hospital',
      'Omandur Hospital',
      NULL,
      13.0689,
      80.2736,
      'Foundation',
      'Free',
      '{"start":"03:00"}'::jsonb,
      NULL,
      NULL,
      'Organized by TNTJ Pudupet Division — Pre-booking at 15:00',
      ARRAY['Free','PreBookingRequired','HospitalFocus']::text[],
      ARRAY['Hospital patients','Families','Caretakers']::text[],
      NULL,
      NULL
    ),
(
      53,
      'TNTJ Sehri – Gosha Hospital',
      'Chennai',
      'Egmore',
      'Gosha Hospital',
      'Gosha Hospital',
      NULL,
      13.0739,
      80.2795,
      'Foundation',
      'Free',
      '{"start":"03:00"}'::jsonb,
      NULL,
      NULL,
      'Organized by TNTJ Pudupet Division — Pre-booking at 15:00',
      ARRAY['Free','PreBookingRequired','HospitalFocus']::text[],
      ARRAY['Hospital patients','Families','Caretakers']::text[],
      NULL,
      NULL
    ),
(
      54,
      'TNTJ Sehri – Egmore Government Maternity & Baby Hospital',
      'Chennai',
      'Egmore',
      'Govt Hospital',
      'Egmore Government Maternity & Baby Hospital',
      NULL,
      13.074,
      80.262,
      'Foundation',
      'Free',
      '{"start":"03:00"}'::jsonb,
      NULL,
      NULL,
      'Organized by TNTJ Pudupet Division — Pre-booking at 15:00',
      ARRAY['Free','PreBookingRequired','HospitalFocus']::text[],
      ARRAY['Hospital patients','Families','Caretakers']::text[],
      NULL,
      NULL
    ),
(
      55,
      'Karpom Karpipom Foundation Sehri Centre',
      'Chennai',
      'Tambaram',
      'Kasturibhai Nagar, West Tambaram',
      'No.118, Kalyansundaram Street, opposite Barkath Manzil Residence',
      NULL,
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      'Pre-booking at 21:00',
      ARRAY['Free','PreBookingRequired']::text[],
      ARRAY['Students','Hostel/PG residents','Working professionals','Hospital patients','Caretakers']::text[],
      NULL,
      ARRAY['M. Azharudeen','Auto A. Meeran','S. Imran']::text[]
    ),
(
      56,
      'Masjid-e-Mubarak (Avadi)',
      'Chennai',
      'Avadi',
      NULL,
      'Avadi, Chennai 600054',
      NULL,
      13.1,
      80,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Masjid','PreBookingRequired']::text[],
      ARRAY['Non-native students','Working professionals','Competitive exam aspirants']::text[],
      NULL,
      ARRAY['M. Sadaqathullah','H. Thameem Ansari']::text[]
    ),
(
      57,
      'Kolathur Friends Association Sehri Point',
      'Chennai',
      'Kolathur',
      'Wellington Stop',
      'Wellington Stop, near S.S. Hyderabad Biryani',
      NULL,
      13.124,
      80.2121,
      'Foundation',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','PreBookingRequired']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      58,
      'Eidgah Masjid (Mandaveli)',
      'Chennai',
      'Mandaveli',
      NULL,
      'Mandaveli, Chennai 600028',
      NULL,
      13.0292,
      80.2653,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Masjid','PreBookingRequired','TokenRequired']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      59,
      'Masjid-e-Hussainiya Youth Wing',
      'Chennai',
      'Moolakadai',
      'Periyar Nagar',
      'No.22, Masjid Street, Periyar Nagar',
      NULL,
      13.1291,
      80.2415,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Masjid','PreBookingRequired']::text[],
      NULL,
      NULL,
      ARRAY['Anwar Basha','Naveed Ahmed','Mohammed Siddiq Ahmed']::text[]
    ),
(
      60,
      'India Towheed Jamaath (INTJ) – State HQ Sehri Centre',
      'Chennai',
      'Chennai Central',
      'State HQ',
      NULL,
      NULL,
      13.0906,
      80.2858,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','PreBookingRequired']::text[],
      ARRAY['Working professionals','Non-native students','Hostel residents','Government officials']::text[],
      NULL,
      ARRAY['Firdaus (State Treasurer)']::text[]
    ),
(
      61,
      'Yaa Mohaideen Biryani (Pallavaram)',
      'Chennai',
      'Pallavaram',
      NULL,
      'Pallavaram, Chennai 600043',
      NULL,
      12.9699,
      80.1417,
      'Restaurant',
      'Paid',
      '{"start":"03:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','PreBookingRequired']::text[],
      NULL,
      NULL,
      ARRAY['Sardar','Thoufiq','Yasir','Abu Bakr','Umar','Mohammed Ali','Mohammed Meeran']::text[]
    ),
(
      62,
      'Masjid-e-Noor Sunnath Masjid (Sothupakkam)',
      'Chennai',
      'Madhavaram',
      'Sothupakkam',
      'Sothupakkam',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"takeaway":"22:15 - 23:00","in_masjid":"03:00 - 04:00"}'::jsonb,
      NULL,
      NULL,
      'Booking: 10:00–18:00 — Doorstep delivery for physically challenged',
      ARRAY['Free','Masjid','PreBookingRequired','TakeawayAvailable','DisabledDelivery']::text[],
      ARRAY['Non-native students','Working professionals','Hospital patients','Caretakers']::text[],
      NULL,
      NULL
    ),
(
      63,
      'Masjid-e-Anwari (Kamarajapuram)',
      'Chennai',
      'Tambaram',
      'Kamarajapuram',
      'Kamarajapuram, Chennai 600073',
      NULL,
      12.9219,
      80.1544,
      'Masjid',
      'Free',
      '{"start":"03:00"}'::jsonb,
      NULL,
      NULL,
      'Booking: 16:00–19:00 — Covers West Tambaram → Medavakkam route',
      ARRAY['Free','Masjid','PreBookingRequired','BachelorsOnly']::text[],
      ARRAY['Bachelors']::text[],
      NULL,
      NULL
    ),
(
      64,
      'MGM Classy Men''s Hostel (Karapakkam, OMR)',
      'Chennai',
      'Karapakkam',
      'OMR',
      'No.3, Easwaran Street, Karapakkam, Chennai 600097',
      NULL,
      12.9142,
      80.2294,
      'Hostel',
      'Free',
      '{"start":"23:00","end":"01:00"}'::jsonb,
      NULL,
      NULL,
      'Booking: 10:00–17:00 — Doorstep delivery for women in PGs/Hostels',
      ARRAY['Free','PreBookingRequired','BringContainer','WomenDelivery']::text[],
      ARRAY['Bachelors','Hostel/PG students','Working professionals']::text[],
      NULL,
      NULL
    ),
(
      65,
      'Al Jabbar Foundation Sehri Centre (T. Nagar)',
      'Chennai',
      'T. Nagar',
      'Usman Road',
      'No.40, Sarojini Street, Usman Road, near Al Jabbar Restaurant',
      NULL,
      13.0418,
      80.2341,
      'Foundation',
      'Free',
      NULL,
      'From March 10 onwards',
      NULL,
      'Tokens issued on March 3–4',
      ARRAY['Free','PreBookingRequired','TokenRequired']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      66,
      'Ar Rahman Islamic Taqwa Centre (ARITC)',
      'Chennai',
      'Chromepet',
      'Lakshmi Nagar',
      'No.57/58, Lakshmi Nagar, 2nd Cross Street, Heena Tower, Chromepet, Chennai 600044',
      NULL,
      12.9467,
      80.1475,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','WomenOnly','ChildrenFocus']::text[],
      ARRAY['Women','Children']::text[],
      NULL,
      ARRAY['Mohammed Ibrahim']::text[]
    ),
(
      67,
      'Madarassa-ul-Hadi (Medavakkam)',
      'Chennai',
      'Medavakkam',
      NULL,
      'No.6/151, Kamarajar Street, near Ponram Hardwares',
      NULL,
      NULL,
      NULL,
      'Masjid',
      'Free',
      '{"start":"21:30","end":"23:00"}'::jsonb,
      NULL,
      NULL,
      'Booking: 10:00–18:00 — Early takeaway-focused',
      ARRAY['Free','Masjid','PreBookingRequired','BachelorsOnly','TakeawayAvailable']::text[],
      ARRAY['Bachelors','Travelers']::text[],
      NULL,
      NULL
    ),
(
      68,
      'Sahabas of Badr Memorial Sehri Centre (Padi Jummah Masjid)',
      'Chennai',
      'Padi',
      NULL,
      'Padi, Chennai 600050',
      NULL,
      13.1014,
      80.1906,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Identity card issued by masjid office',
      ARRAY['Free','Masjid','PreBookingRequired']::text[],
      ARRAY['Non-native students','Professionals in lodgings']::text[],
      NULL,
      NULL
    ),
(
      3001,
      'Masjid Jamia Islamabad',
      'Bengaluru',
      'Basavanagudi',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      'Basavanagudi Only',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9341625054','9886711625']::text[],
      ARRAY['Syed Waseem']::text[]
    ),
(
      3002,
      'Abu Bakar Masjid',
      'Bengaluru',
      'Chamrajpet',
      'Vinayaka Nagar, Padarayanapura',
      '13th Cross Road, Vinayaka Nagar, Padarayanapura, Bengaluru 560026',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      ARRAY['9341211075']::text[],
      ARRAY['Aman']::text[]
    ),
(
      3003,
      'Ansaar Masjid, Kaggalipura',
      'Bengaluru',
      'Kaggalipura',
      NULL,
      'Near Ravi Shankar Ashram',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      ARRAY['9844356687']::text[],
      ARRAY['Azmath']::text[]
    ),
(
      3004,
      'Benevolent Welfare Group, Kaval Byrasandra',
      'Bengaluru',
      'Kaval Byrasandra',
      'Shampur, LR Nagar',
      'LR Bande Road, Shampura, Kaval Byrasandra, Bengaluru, Karnataka 560032',
      'Bengaluru North',
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9986014736']::text[],
      ARRAY['Syed Fareed Ahmed']::text[]
    ),
(
      3005,
      'Bismillah Mubarak Hotel, Whitefield',
      'Bengaluru',
      'Whitefield',
      NULL,
      '452, Behind Govt. School, Shop-I, Gandhipuram, Whitefield, Bengaluru - 560066',
      'Bengaluru East',
      NULL,
      NULL,
      'Hotel',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','Delivery']::text[],
      NULL,
      ARRAY['9880620147']::text[],
      ARRAY['Imran']::text[]
    ),
(
      3006,
      'Dry Fruit House, AECS Layout Brookfield',
      'Bengaluru',
      'Brookefield',
      'Hoodi, Brookfield',
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Restaurant',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8880008765','8904571055']::text[],
      ARRAY['Syed Yusuf']::text[]
    ),
(
      3007,
      'Hoskote Sehri Distribution',
      'Bengaluru',
      'Hoskote',
      NULL,
      'AR Extn, Old Madras Road, 50 mtrs From Makkah Masjid',
      'Bengaluru East',
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9880376126','9448249254']::text[],
      ARRAY['Mohammad Afzal Pasha']::text[]
    ),
(
      3008,
      'Jafar Musallah',
      'Bengaluru',
      'Kothanur',
      NULL,
      'Channa Keshava Complex, Kristu Jayanti College, 34/3, Kothanur, Bengaluru',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7829147008','9945696883','8217085409']::text[],
      ARRAY['Mohammed Anas']::text[]
    ),
(
      3009,
      'Jamia Kamees Bin Mubarak Masjid',
      'Bengaluru',
      'DJ Halli',
      NULL,
      'Modi Road, DJ Halli, Bengaluru',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      ARRAY['9590064545','9141684312']::text[],
      ARRAY['Firdoze Akhtar']::text[]
    ),
(
      3010,
      'Jamia Masjid, Basaveswara Nagar',
      'Bengaluru',
      'Basaveshwara Nagar',
      NULL,
      '79, 17th Cross KBH Colony, Basaveshwara Nagar',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','Delivery']::text[],
      NULL,
      ARRAY['9343729984']::text[],
      ARRAY['Rahmat']::text[]
    ),
(
      3011,
      'Jamia Masjid, Budumanahalli',
      'Bengaluru',
      'Presidency College area',
      NULL,
      '4 kms From Presidency College',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9035452495','9900101987','9035406507']::text[],
      ARRAY['Maaz']::text[]
    ),
(
      3012,
      'Jamia Masjid, Noba Nagar',
      'Bengaluru',
      'Bannerghatta Road',
      NULL,
      'Nobo Nagar, Kalena Agrahara, Bannerghatta Road, Bengaluru, 560076',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      ARRAY['9902811065','7019340008','9717225864']::text[],
      ARRAY['Afsar Bhai']::text[]
    ),
(
      3013,
      'Makkah Masjid, Yelahanka',
      'Bengaluru',
      'Yelahanka',
      NULL,
      '17th Cross, 1st Main, Maruthi Nagar, Yelahanka, Bengaluru',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      ARRAY['9880489764','934109764']::text[],
      ARRAY['Irfan']::text[]
    ),
(
      3014,
      'Jamia Masjid, Soladevanahalli',
      'Bengaluru',
      'Soladevanahalli',
      NULL,
      'MSPP Colony Road, Near Sri Lakshmi Venkateswara Swami Devasthana, Soladevanahalli, Bengaluru 560107',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9341853971']::text[],
      ARRAY['Anwar Basha']::text[]
    ),
(
      3015,
      'Jamia Masjid, Ulsoor',
      'Bengaluru',
      'Ulsoor',
      NULL,
      'Gupta Layout, Ulsoor, Bengaluru',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9845384631']::text[],
      ARRAY['Mohammed Nafees']::text[]
    ),
(
      3016,
      'Jamia Masjid, Yeswanthpur',
      'Bengaluru',
      'Yeshwanthpur',
      NULL,
      'Opposite RTO, Dr.Ambedkar Nagar, Yeswanthpur, Bengaluru, Karnataka 560022',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9035709733','9845008236','6363202731']::text[],
      ARRAY['Syed Saquib Ahmed']::text[]
    ),
(
      3017,
      'Jamiya Masjid, Shikaripalya',
      'Bengaluru',
      'Shikaripalya',
      NULL,
      'Shikaripalya Jamiya Masjid, Neeladrinagar 2nd Cross, Neeladrinagar 4th Cross',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9900001439','6360397593']::text[],
      ARRAY['Shaik Mubarak']::text[]
    ),
(
      3018,
      'Jamiya Masjid, Kadugodi',
      'Bengaluru',
      'Kadugodi / Whitefield',
      'Prashanth Layout',
      'Kadugodi, Prashanth Layout, Whitefield, Bengaluru',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['7349119552','8073959624']::text[],
      ARRAY['Hussain Basha']::text[]
    ),
(
      3019,
      'Jamia Masjid, Rahamath Nagar',
      'Bengaluru',
      'RT Nagar / Hebbal',
      NULL,
      'Jamia Masjid Rahamathnagar, RT Nagar Post. Location Near Sreeraj Lassi Bar RT Nagar Main Road',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8904244437','7795533109']::text[],
      ARRAY['Syed Zabi']::text[]
    ),
(
      3020,
      'All India Milli Council, Bengaluru',
      'Bengaluru',
      'Shampur',
      NULL,
      'Ambedkar Medical College, Shampur Road',
      'Bengaluru North',
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9620837786']::text[],
      ARRAY['Syed Mazhar']::text[]
    ),
(
      3021,
      'Jamiya Masjid & Madrasa E Arabia Kashiful Uloom',
      'Bengaluru',
      'Vidyaranya Nagar',
      NULL,
      'No. 169/1 Old No. 4/A, 7th Cross Vidyaranya Nagar Hosahalli Extension Magadi Road',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9739084347','9880788675']::text[],
      ARRAY['Matheen Ahmed']::text[]
    ),
(
      3022,
      'Hira Masjid, Bapuji Nagar',
      'Bengaluru',
      'Bapuji Nagar',
      NULL,
      'Hira Masjid, 13th Cross, 1st Main Road, Bapujinagar, Bengaluru - 560026',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8660622775','9916676840']::text[],
      ARRAY['Syed Saleem']::text[]
    ),
(
      3023,
      'Masjid E Abubakar Siddiq R.A',
      'Bengaluru',
      'Manyata Tech Park / Saraipalya',
      NULL,
      'Saraipalya, Manyata Tech Park Sinthan Nagar, Bengaluru',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9141613381','9342410242']::text[],
      ARRAY['Salman Yousuf']::text[]
    ),
(
      3024,
      'Madani Dastarkhan, Neelsandra',
      'Bengaluru',
      'Neelasandra',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9620229007','9611999127','8971777703','9886160059']::text[],
      ARRAY['Akram']::text[]
    ),
(
      3025,
      'Madeena Masjid (Sunni)',
      'Bengaluru',
      'Ashwath Nagar / Sanjay Nagar',
      NULL,
      '180, 80 Feet Road, Met Layout, Geddalahalli, Sanjayanagara, Bengaluru, Karnataka 560094',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9738129786','9972246785']::text[],
      ARRAY['Syed Ismail Shah']::text[]
    ),
(
      3026,
      'Madiwala Minority Welfare Trust',
      'Bengaluru',
      'Madiwala / Koramangala',
      NULL,
      'Tavarakere, Madiwala, Koramangala, Maruthi Nagar, Suddagunte Palya',
      'Bengaluru South',
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8050556895']::text[],
      ARRAY['Shoaib Pasha']::text[]
    ),
(
      3027,
      'Makkah Masjid Trust, Ramamurthy Nagar',
      'Bengaluru',
      'Ramamurthy Nagar',
      NULL,
      '78/1, Kowdenahalli, Ramamurthy Nagar, Bengaluru, Karnataka - 560016',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9538043326','9916092540','9844589654']::text[],
      ARRAY['Suhail S']::text[]
    ),
(
      3028,
      'Masjid Al Aziz, Manyata Tech Park',
      'Bengaluru',
      'Manyata Tech Park (Nagawara)',
      NULL,
      NULL,
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','DineIn']::text[],
      NULL,
      ARRAY['9611295583','8083033548']::text[],
      ARRAY['Ashfaque Ahmed']::text[]
    ),
(
      3029,
      'Masjid Al Qasim',
      'Bengaluru',
      'Kudlu Gate / Muneshwara Nagar',
      NULL,
      'Kudlu Gate, Bank Colony, HAL Layout, Muneshwara Nagar, Bengaluru 560068',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9448260564','9019794296']::text[],
      ARRAY['Syed Maaz Ahmed']::text[]
    ),
(
      3030,
      'Masjid E Aftab and Masjid E Aqsa (Doddakannelli)',
      'Bengaluru',
      'Doddakannelli / Carmelaram',
      NULL,
      'Carmelaram, Janatha Colony, Doddakannelli, Bengaluru',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn','Delivery']::text[],
      NULL,
      ARRAY['9986687733','9940836519']::text[],
      ARRAY['Abdul Aleem']::text[]
    ),
(
      3031,
      'Masjid E Ali Abul Hasnain, Lakkasandra',
      'Bengaluru',
      'Lakkasandra / Nimhans area',
      NULL,
      'Nimhans area, Lakkasandra, Bengaluru - 560030',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8310612674','9066786714']::text[],
      ARRAY['Shahid']::text[]
    ),
(
      3032,
      'Masjid E Ameer Hamza',
      'Bengaluru',
      'Gandhinagar / Madapattana',
      NULL,
      'Madapattana 1.5-2 Km From Jigani, Behind Petrol Pump',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9845029497']::text[],
      ARRAY['Mudassir']::text[]
    ),
(
      3033,
      'Masjid E Aqsa O Madrasa, HSR Layout',
      'Bengaluru',
      'HSR Layout',
      NULL,
      '1418, 2, 1st Nain Road, Sector 6, HSR Layout, Bengaluru 560068',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','Delivery','DineIn']::text[],
      NULL,
      ARRAY['9035600000']::text[],
      ARRAY['Amjad']::text[]
    ),
(
      3034,
      'Masjid E Bilal, Yelahanka New Town',
      'Bengaluru',
      'Yelahanka',
      NULL,
      '6th Main Road, Yelahanka New Town 5th Phase',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9945761365','9620193707']::text[],
      ARRAY['Irshad Ahmed']::text[]
    ),
(
      3035,
      'Masjid E Bilal, K R Puram',
      'Bengaluru',
      'KR Puram / T C Palya',
      NULL,
      'T C Palya / Bhattarahalli / Garden City College area',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9886346635']::text[],
      ARRAY['Safeer']::text[]
    ),
(
      3036,
      'Masjid E Fayaz',
      'Bengaluru',
      'Bommasandra',
      NULL,
      'RK Lake View 6th Cross Masjid E Fayaz, Hebbagodi, Bommasandra, Bangalore - 560099',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9686526985','9611190649']::text[],
      ARRAY['Syed Afreed']::text[]
    ),
(
      3037,
      'Masjid E Khasimiya, Murgesh Palya',
      'Bengaluru',
      'Murgeshpalya',
      NULL,
      '107, Murugeshpalya, Ramagiri, Bengaluru 560017',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7411040066','9980834018','9503062554']::text[],
      ARRAY['Mohammed Shuaib']::text[]
    ),
(
      3038,
      'Masjid E Ibadat Khana (BTM)',
      'Bengaluru',
      'BTM Layout / NS Palya',
      NULL,
      'Behind Shoppers Stop, 5th Cross, 1st Main, Bannerghatta Road, NS Palya, Stage 2',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9986688141']::text[],
      ARRAY['Tabrezulla']::text[]
    ),
(
      3039,
      'Masjid E Ashrafiya, Rajajinagar',
      'Bengaluru',
      'Rajajinagar',
      NULL,
      'Ramamohanapuram, Rajajinagar, Bengaluru (Mahakavi Kuvempu Road, 560021)',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7019044517','9513016074']::text[],
      ARRAY['Jaffer']::text[]
    ),
(
      3040,
      'Madina Hotel, Whitefield',
      'Bengaluru',
      'Whitefield',
      NULL,
      'Whitefield',
      'Bengaluru East',
      NULL,
      NULL,
      'Hotel',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','Delivery']::text[],
      NULL,
      ARRAY['6361700345']::text[],
      ARRAY['Mujahid Pasha']::text[]
    ),
(
      3041,
      'TEAM KHIDMAT BOYS',
      'Bengaluru',
      'Ulsoor / HBR / Frazer Town area',
      NULL,
      'Ulsoor, Lingarajapuram, Oil Mill road, Banaswadi, Cox town, Frazer town, Kammanahalli, HBR layout',
      'Bengaluru North',
      NULL,
      NULL,
      'Group',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8660546693','9902525901']::text[],
      ARRAY['Musadiq Ahmed']::text[]
    ),
(
      3042,
      'Masjid E Abdus Subhan, Tavarekere (Ladies only)',
      'Bengaluru',
      'Tavarekere / BTM',
      NULL,
      'BTM Layout I Stage area',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'For ladies only',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9906687379','9886043243']::text[],
      ARRAY['Umar Basheer']::text[]
    ),
(
      3043,
      'Makkah Masjid (Electronic City / Shikaripalya)',
      'Bengaluru',
      'Shikaripalya / Electronic City Phase 1',
      NULL,
      'Shikaripalya, Electronic City Phase 1, Bengaluru - 560100',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['+919535325430','+917899400203']::text[],
      ARRAY['Sharique Umar']::text[]
    ),
(
      3044,
      'Masjid e Ameena (Devarabeesanahalli / Bellandur)',
      'Bengaluru',
      'Devarabeesanahalli / Marathahalli',
      NULL,
      'Adarsh Palm Retreat, Bellandur, Bengaluru, Karnataka 560103',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9742117247']::text[],
      ARRAY['Azad']::text[]
    ),
(
      3045,
      'Masjid E Khudadad, Marathahalli',
      'Bengaluru',
      'Marathahalli',
      NULL,
      'SS Chambers, 4th Floor, 32, Service Road, Aswath Nagar, Marathahalli, Bengaluru 560037',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9542521312','7259692506']::text[],
      ARRAY['Hussain']::text[]
    ),
(
      3046,
      'Masjid E Mahmoodiya, K R Puram',
      'Bengaluru',
      'KR Puram',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Haji Layout / Cambridge College / Sea College coverage',
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9844034502']::text[],
      ARRAY['Rehan Patel']::text[]
    ),
(
      3047,
      'Masjid E Mina, C V Raman Nagar',
      'Bengaluru',
      'CV Raman Nagar',
      NULL,
      'Varthur Road Nagavarapalya, C V Raman Nagar Bengaluru, Karnataka 560093',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9590186182']::text[],
      ARRAY['Sharukh']::text[]
    ),
(
      3048,
      'Masjid E Mohammadia (Peenya)',
      'Bengaluru',
      'Peenya / Dasarahalli',
      NULL,
      'Peenya, Behind Dasarahalli Metro Station',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['8904697851']::text[],
      ARRAY['Shoaib Bhai']::text[]
    ),
(
      3049,
      'Masjid E Moiniya, Yeshwanthpur',
      'Bengaluru',
      'Yeshwanthpur',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Yeshwanthpur only',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9880054638','8660451428']::text[],
      ARRAY['Mohammed Khan']::text[]
    ),
(
      3050,
      'Masjid E Nimra (Padarayanapura)',
      'Bengaluru',
      'Padarayanapura',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9845130255']::text[],
      ARRAY['Mujahid']::text[]
    ),
(
      3051,
      'Masjid E Noor (Muneshwara Nagar)',
      'Bengaluru',
      'Muneshwara Nagar',
      NULL,
      '22/23, 3rd Cross Rd, Bandepalya, Muneshwara Nagar, Bengaluru 560068',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['7899933011']::text[],
      ARRAY['Syed Nawaz']::text[]
    ),
(
      3052,
      'Masjid E Noor (Thanisandra)',
      'Bengaluru',
      'Thanisandra',
      NULL,
      '157 4 Cross Unity Nagar, Noor Masjid Road, Thanisandra, Bengaluru',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7353044061','9739369947']::text[],
      ARRAY['Syed Irfan']::text[]
    ),
(
      3053,
      'Masjid E Qamrunnisa, K R Puram',
      'Bengaluru',
      'KR Puram / Medahalli',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Medahalli / Bidarahalli / East Point College coverage',
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9845328447']::text[],
      ARRAY['Mudassir']::text[]
    ),
(
      3054,
      'Masjid E Quba, Kalasipalyam',
      'Bengaluru',
      'Kalasipalyam',
      NULL,
      'Kalasipalyam',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9591068750']::text[],
      ARRAY['Syed Faiz Ahmed']::text[]
    ),
(
      3055,
      'Masjid E Rahmania, Sanjay Nagar',
      'Bengaluru',
      'Sanjay Nagar',
      NULL,
      'Masjid E Rahmania, Raj Mahal Vilas 2nd Stage, Sanjay Nagar, Bengaluru 560094',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9900398420','9343826238']::text[],
      ARRAY['Ismail Zabiullah']::text[]
    ),
(
      3056,
      'Masjid E Rasheedia, Govindpur & Nagawara',
      'Bengaluru',
      'Nagawara / Govindpura',
      NULL,
      'Byrappa Layout, Nagawara, Bengaluru 560045',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['7899917760']::text[],
      ARRAY['Tahseen Ahmed']::text[]
    ),
(
      3057,
      'Masjid E Rizwan (JP Nagar)',
      'Bengaluru',
      'JP Nagar',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9972045466','8105666956']::text[],
      ARRAY['Siddique']::text[]
    ),
(
      3058,
      'Masjid E Tauheed (Goripalya / Mysore Road)',
      'Bengaluru',
      'Goripalya / Mysore Road',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9845645104']::text[],
      ARRAY['Nasir']::text[]
    ),
(
      3059,
      'Masjid E Tawakkal (Hennur)',
      'Bengaluru',
      'Hennur / Baglur',
      NULL,
      'Hennur, Baglur Main Road',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9341072935']::text[],
      ARRAY['Abdurraheem']::text[]
    ),
(
      3060,
      'Masjid E Tippu, Marathahalli',
      'Bengaluru',
      'Marathahalli',
      NULL,
      'PSA Plaza, HAL Old Airport Road, Opp Naveen Kala Showroom',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9343549356']::text[],
      ARRAY['Syed Ahmed']::text[]
    ),
(
      3061,
      'Masjid E Touheed (Dooravani Nagar)',
      'Bengaluru',
      'Dooravani Nagar',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      ARRAY['9845921110','9945909781','9845368826','9686360569']::text[],
      ARRAY['Syed Ataulla']::text[]
    ),
(
      3062,
      'Masjid Faiz E Umar Eidgah, JHBCS Layout Minhaj Nagar',
      'Bengaluru',
      'Minhaj Nagar',
      NULL,
      'Eidgah Masjid Faiz-E-Umar Eidgah, J.H.B.C.S Layout Minhaj Nagar, Bengaluru- 560078',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['9886107861','9845298454']::text[],
      ARRAY['Sharif']::text[]
    ),
(
      3063,
      'Masjid Jolly Mohalla (BMM Groups), Sultanpet',
      'Bengaluru',
      'KR Market',
      NULL,
      'Masjid-E-Jolly Mohalla, Near KR Market, Sultanpete',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8904762822','6360572246']::text[],
      ARRAY['Mukhtiyar']::text[]
    ),
(
      3064,
      'Masjid Noor, Mango Garden',
      'Bengaluru',
      'Off Kanakapura Road',
      NULL,
      'Masjid Noor, Mango Garden, Bikasipura Road, Off Kanakapura Road, Bengaluru - 560111',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9886374006','9353161611']::text[],
      ARRAY['Harun']::text[]
    ),
(
      3065,
      'Masjid E Moazzam (Bismillahnagar)',
      'Bengaluru',
      'Bismillahnagar',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9738126760']::text[],
      ARRAY['Mohammed Atif']::text[]
    ),
(
      3066,
      'Masjid E Quba (Gents) BTM Layout',
      'Bengaluru',
      'BTM Layout',
      NULL,
      '604, 29th Main Rd, EWS Colony, BTM Layout 2nd Stage',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['7829556958']::text[],
      ARRAY['Saleem']::text[]
    ),
(
      3067,
      'Masjid E Moazzam (Opp BTM water tank)',
      'Bengaluru',
      'BTM Layout',
      NULL,
      'Opposite BTM Layout Water Tank Bus Stop',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9845828778','9342636348']::text[],
      ARRAY['Humayun Bhai']::text[]
    ),
(
      3068,
      'Masjid E Rahmaniya (Jigani)',
      'Bengaluru',
      'Jigani',
      NULL,
      'Vegetable Market, Opp. Police Station, Ittina Nagar, Jigani, Karnataka 560105',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9739999314','9591087616']::text[],
      ARRAY['Hussain']::text[]
    ),
(
      3069,
      'Masjid E Umar Bin Khattab, Govindpur & Nagawara',
      'Bengaluru',
      'Govindpura / Nagawara',
      NULL,
      NULL,
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','Delivery']::text[],
      NULL,
      ARRAY['9743157732','9880804924']::text[],
      ARRAY['Ismail']::text[]
    ),
(
      3070,
      'Masjid-E-Ayesha',
      'Bengaluru',
      'Bommanahalli / Mangammana Palya',
      NULL,
      'Mangammana Palya, Kudlu Gate, HSR Layout, Sector ...',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['7899933011']::text[],
      ARRAY['Syed Nawaz']::text[]
    ),
(
      3071,
      'Masjid-E-Ghousia, Youth Sehri Group (Nandini Layout)',
      'Bengaluru',
      'Nandini Layout',
      NULL,
      'No. 19/50, 2nd Main Road, Nanjundeshwara Nagar, Nandini Layout, Bengaluru 560096',
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9986786717','9916464278','9845315015']::text[],
      ARRAY['Imran']::text[]
    ),
(
      3072,
      'Masjid-E-Haadi (KR Puram)',
      'Bengaluru',
      'KR Puram',
      NULL,
      'Masjid E Hadi, Devasandra, KR Puram, Bengaluru-560036',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9535259646','8867793539']::text[],
      ARRAY['Hameed']::text[]
    ),
(
      3073,
      'Masjid-E-Sara (Meenakshi Layout)',
      'Bengaluru',
      'Meenakshi Layout',
      NULL,
      'Near Central Jail, Meenakshi Layout',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9880190020']::text[],
      ARRAY['Shaikh S Muneer']::text[]
    ),
(
      3074,
      'Masjid-E-Talha, Whitefield',
      'Bengaluru',
      'Whitefield / Garudachar Palya',
      NULL,
      'Minority Education Trust (MET), #8, 5th, Main, Garudachar Palya, Whitefield',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','DineIn']::text[],
      NULL,
      ARRAY['9066384999','9845090851','9449233556']::text[],
      ARRAY['Syed Nadeem']::text[]
    ),
(
      3075,
      'Masjid-E-Ummul Hasnain, Indiranagar',
      'Bengaluru',
      'Indiranagar',
      NULL,
      'Indira Nagar 1st Stage, HAJ Colony, Indiranagar',
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9986683223','8892392282']::text[],
      ARRAY['Mohammed Ashraf']::text[]
    ),
(
      3076,
      'Masjid-E-Uqba, Saraipalya (Thanisandra)',
      'Bengaluru',
      'Thanisandra',
      NULL,
      'Madeena Tea Stall, Thanisandra (Behind Manyata Tech Park)',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9945119164']::text[],
      ARRAY['Masood']::text[]
    ),
(
      3077,
      'Meenar Masjid, 5th Block Jayanagar',
      'Bengaluru',
      'Jayanagar',
      NULL,
      'MTB Area Jayanagar 5th Block',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9980334679','7676405860','9343401013','7349547816']::text[],
      ARRAY['Naseer']::text[]
    ),
(
      3078,
      'MMYC Bengaluru (multiple hospital zones)',
      'Bengaluru',
      'Multiple (Hospitals)',
      NULL,
      'Jayadeva Hospital, Nimhans, Sanjay Gandhi Hospital, Jayanagar, Victoria Hospital, KR Market ...',
      'Bengaluru South',
      NULL,
      NULL,
      'Group',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9066604090']::text[],
      ARRAY['Abubakar']::text[]
    ),
(
      3079,
      'Noor Masjid, Noor Nagar',
      'Bengaluru',
      'Chokkanahalli',
      NULL,
      'Noor Nagar, Chokkanahalli',
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Paid',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid']::text[],
      NULL,
      ARRAY['8123334673','9108304761']::text[],
      ARRAY['Munawar']::text[]
    ),
(
      3080,
      'Noor Sehri Delivery (Manyata Tech Park / Thanisandra)',
      'Bengaluru',
      'Thanisandra',
      NULL,
      '19, Amarjothi Layout, Rachenahalli Main Road, Thanisandra',
      'Bengaluru North',
      NULL,
      NULL,
      'Service',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9591137455','8618081294']::text[],
      ARRAY['Mohammed Khalid Pasha']::text[]
    ),
(
      3081,
      'Noorani Masjid (Garvebhavi Palya)',
      'Bengaluru',
      'Garvebhavi Palya',
      NULL,
      '38/5A, Bandepalya, Garvebhavi Palya, Bengaluru 560068',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7899933011']::text[],
      ARRAY['Syed Nawaz']::text[]
    ),
(
      3082,
      'POD Hostels (Nagasandra)',
      'Bengaluru',
      'Nagasandra',
      NULL,
      'Pod Hostels, HMT Layout, Nagasandra, Near Nagasandra Metro Station',
      'Bengaluru North',
      NULL,
      NULL,
      'Hostel',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      ARRAY['8660066994','9886625960']::text[],
      ARRAY['Riyaz']::text[]
    ),
(
      3083,
      'Ramadan Sehri (Dinnur)',
      'Bengaluru',
      'Dinnur',
      NULL,
      'Dinnur, Opposite Novodaya School',
      'Bengaluru North',
      NULL,
      NULL,
      'Service',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7019588329','9945786387']::text[],
      ARRAY['Moin Ahmed']::text[]
    ),
(
      3084,
      'Ramzan Sehri, Kengeri',
      'Bengaluru',
      'Kengeri',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['8892546619']::text[],
      ARRAY['Mohammad Khan']::text[]
    ),
(
      3085,
      'Royal Hotel, Bannerghatta Road',
      'Bengaluru',
      'Jayadeva Hospital',
      NULL,
      'Near Jayadeva Hospital, Bannerghatta Road',
      'Bengaluru South',
      NULL,
      NULL,
      'Hotel',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7892598975']::text[],
      ARRAY['Ahmad']::text[]
    ),
(
      3086,
      'Sarjapur Youth Group',
      'Bengaluru',
      'Sarjapur',
      NULL,
      'Barkath Hotel, Near Sarjapura, Jamia Masjid',
      'Bengaluru East',
      NULL,
      NULL,
      'Group',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9901307103','9740141837']::text[],
      ARRAY['Syed Salamath']::text[]
    ),
(
      3087,
      'Sehri Takeaway, Vasanth Nagar',
      'Bengaluru',
      'Vasanth Nagar',
      NULL,
      'Ma Milk Parlour, Vasanth Nagar',
      'Bengaluru East',
      NULL,
      NULL,
      'Service',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9901201562','9611145220','8618422823']::text[],
      ARRAY['Imran']::text[]
    ),
(
      3088,
      'SRK Convention Center, Neelsandra',
      'Bengaluru',
      'Neelasandra',
      NULL,
      'S.R.K Convention Centre, Bazaar St. Richard Xavier''s Colony, Neelasandra, Bengaluru - 560047',
      'Bengaluru South',
      NULL,
      NULL,
      'Convention Center',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9620508786']::text[],
      ARRAY['Nooman Zaid Khan']::text[]
    ),
(
      3089,
      'Masjid Umar Farooq, Byrasandra',
      'Bengaluru',
      'Byrasandra / Jayanagar',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Covers Jayadeva Hospital, NIMHANS area etc.',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9945480572','9343826635']::text[],
      ARRAY['Tailor Iqbal Pasha']::text[]
    ),
(
      3090,
      'Royal Palace Function Hall (Next To Masjid Ateeq)',
      'Bengaluru',
      'Wilson Garden / Lakkasandra',
      NULL,
      '#23, Near Brand Factory, Next to Abhaya Hospital, Wilson Garden Bangalore - 560027',
      'Bengaluru South',
      NULL,
      NULL,
      'Hall',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9071583247','8553421550']::text[],
      ARRAY['Mohammed Athar']::text[]
    ),
(
      3091,
      'Masjid Umar Bin Khattab, Anekal',
      'Bengaluru',
      'Anekal / Marsur',
      NULL,
      'No 80, Opp Masjid E Umar Bin Khattab, Hosur Road',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['9036148962','9035821257']::text[],
      ARRAY['Farhathulla Baig']::text[]
    ),
(
      3092,
      'Sunshine School (Madrasa Talim Ul Quran), Chikka Banavara',
      'Bengaluru',
      'Chikkabanavara',
      NULL,
      'Near Sunshine School, Medaralli, Chikkabanavara, Karnataka 560090',
      'Bengaluru West',
      NULL,
      NULL,
      'Madrasa',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7702399682','8217442489']::text[],
      ARRAY['Asif Iqbal']::text[]
    ),
(
      3093,
      'Tipu Sultan Masjid',
      'Bengaluru',
      'JP Nagar',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Avalahalli, JP Nagar 9th Phase',
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9880526108','7019582979','9036684444','9916600129']::text[],
      ARRAY['Shaik Kudrath']::text[]
    ),
(
      3094,
      'WakeUp Hostels (Electronic City / Kudlu Gate)',
      'Bengaluru',
      'Electronic City',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Hostel Group',
      'Free',
      NULL,
      NULL,
      NULL,
      '3 distribution points: Neeladrinagar, Konappana Agrahara, Electronic City Phase 2',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8292387789']::text[],
      ARRAY['Raju Kumar']::text[]
    ),
(
      3095,
      'Sadiq Rahmathulla & Team (Shivajinagar - For ladies only)',
      'Bengaluru',
      'Shivajinagar / Commercial Street area',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Volunteer Group',
      'Free',
      NULL,
      NULL,
      NULL,
      'For ladies only (Shivajinagar, Vasanth Nagar, Cunningham Road etc.)',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['8951669581']::text[],
      ARRAY['Sadiq Rahmathulla']::text[]
    ),
(
      3096,
      'Masjid E Muhajeer, Bommanahalli',
      'Bengaluru',
      'Bommanahalli',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Roopena Agrahara And Oxford College Back Gate, Bommanahalli Only',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7892447107']::text[],
      ARRAY['Syed Zaid']::text[]
    ),
(
      3097,
      'Madeena Masjid (Attibele)',
      'Bengaluru',
      'Attibele, Anekal',
      NULL,
      'Madeena Masjid, Attibele, Anekal Taluk, Bangalore - 562107',
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free']::text[],
      NULL,
      ARRAY['8317421212','9066786794']::text[],
      ARRAY['Nadeem']::text[]
    ),
(
      3098,
      'Masjid E Umme Kulsum',
      'Bengaluru',
      'Bannerghatta Road (multiple coverage areas)',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      'Covers Bilekahalli, Arekere, Hulimavu, Kalena Agrahara, Gottigere, Kalkere, Bannerghatta Circle',
      ARRAY['Free','Delivery']::text[],
      NULL,
      ARRAY['7975266361','9632244147','9343443495']::text[],
      ARRAY['Ameen']::text[]
    ),
(
      3099,
      'All India Milli Council, Bengaluru (Seshadripuram)',
      'Bengaluru',
      'Seshadripuram',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      'Seshadripuram Minority Hostel for working women and girls only',
      ARRAY['Free']::text[],
      NULL,
      ARRAY['9620837786']::text[],
      ARRAY['Syed Mazhar']::text[]
    ),
(
      3100,
      'Adorn Inn (PG / Sehri support)',
      'Bengaluru',
      'Kogilu / Thirumenahalli',
      NULL,
      NULL,
      'Bengaluru North',
      NULL,
      NULL,
      'PG / Hostel',
      'Paid',
      NULL,
      NULL,
      NULL,
      'Adorn Inn Premium PG for Gents - multiple locations',
      ARRAY['Paid']::text[],
      NULL,
      ARRAY['7619414761']::text[],
      ARRAY['Irshad']::text[]
    ),
(
      3101,
      'Masjid E Huda',
      'Bengaluru',
      'Hebbal',
      NULL,
      NULL,
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3102,
      'Jamia Masjid, Jakkur',
      'Bengaluru',
      'Jakkur',
      NULL,
      NULL,
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3103,
      'Masjid E Rahmath',
      'Bengaluru',
      'Kengeri',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3104,
      'Masjid E Bilal',
      'Bengaluru',
      'Malleshwaram',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3105,
      'Masjid E Quba',
      'Bengaluru',
      'Chandra Layout',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3106,
      'Masjid E Tawheed',
      'Bengaluru',
      'Magadi Road',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3107,
      'Jamia Masjid, Chikkabanavara',
      'Bengaluru',
      'Chikkabanavara',
      NULL,
      NULL,
      'Bengaluru North',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3108,
      'Masjid E Ameen',
      'Bengaluru',
      'Mahadevapura',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3109,
      'Masjid E Hidayah',
      'Bengaluru',
      'Varthur',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3110,
      'Bellandur Youth Sehri Group',
      'Bengaluru',
      'Bellandur',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3111,
      'Masjid E Rahmat Ullah',
      'Bengaluru',
      'KR Puram Extension',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3112,
      'Masjid E Mustafa',
      'Bengaluru',
      'Guddadahalli',
      NULL,
      NULL,
      'Bengaluru West',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3113,
      'Masjid E Shifa',
      'Bengaluru',
      'Shivajinagar',
      NULL,
      NULL,
      'Bengaluru East',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3114,
      'Masjid E Taqwa',
      'Bengaluru',
      'Ullal',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      3115,
      'Masjid E Khairunnisa',
      'Bengaluru',
      'Basavanapura',
      NULL,
      NULL,
      'Bengaluru South',
      NULL,
      NULL,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Delivery']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      4001,
      'Juma Masjid',
      'Mumbai',
      'Crawford Market / Marine Lines',
      NULL,
      'Crawford Market, Marine Lines',
      'South Mumbai',
      18.9461,
      72.834,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:30"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','DineIn','TravelerSupport','StudentFriendly']::text[],
      ARRAY['General Public','Travelers']::text[],
      NULL,
      NULL
    ),
(
      4002,
      'Minara Masjid Street Food',
      'Mumbai',
      'Mohammed Ali Road',
      NULL,
      'Minara Masjid',
      'South Mumbai',
      18.9566,
      72.836,
      'Street Food Hub',
      'Paid',
      '{"start":"23:00","end":"04:30"}'::jsonb,
      'Entire Ramadan',
      NULL,
      'Various stalls open for Sehri offering Malpua, Kebabs, and Phirni',
      ARRAY['Paid','OpenAllNight','Famous']::text[],
      ARRAY['Foodies','General Public']::text[],
      NULL,
      NULL
    ),
(
      4003,
      'Noor Mohammadi Hotel',
      'Mumbai',
      'Bhendi Bazaar',
      NULL,
      'Bhendi Bazaar',
      'South Mumbai',
      18.9587,
      72.8354,
      'Restaurant',
      'Paid',
      '{"start":"03:00","end":"04:30"}'::jsonb,
      'Entire Ramadan',
      NULL,
      'Famous for Nalli Nihari and Sanju Baba Chicken',
      ARRAY['Paid','DineIn','AC']::text[],
      NULL,
      ARRAY['022-23456008']::text[],
      NULL
    ),
(
      4004,
      'Al-Iman Charitable Trust',
      'Mumbai',
      'Dongri',
      NULL,
      'Najafi House, Imam Husain Chowk',
      'South Mumbai',
      18.9625,
      72.8375,
      'NGO',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','Takeaway']::text[],
      ARRAY['Needy','Local Community']::text[],
      ARRAY['+912223403295']::text[],
      NULL
    ),
(
      4005,
      'Haji Ali Dargah Trust',
      'Mumbai',
      'Worli',
      NULL,
      'Haji Ali Dargah, Worli Seaface',
      'South Mumbai',
      18.9827,
      72.8089,
      'Dargah',
      'Free',
      '{"start":"03:30","end":"04:30"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','DineIn','WomenSection','TravelerSupport']::text[],
      ARRAY['General Public','Travelers','Needy']::text[],
      ARRAY['+912223529082']::text[],
      NULL
    ),
(
      4006,
      'Mahim Dargah',
      'Mumbai',
      'Mahim West',
      NULL,
      'Mahim Dargah Street',
      'Central Mumbai',
      19.0401,
      72.8359,
      'Dargah',
      'Free',
      '{"start":"03:15","end":"04:15"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','DineIn','Community']::text[],
      ARRAY['Needy','Local Community']::text[],
      ARRAY['7860977860']::text[],
      NULL
    ),
(
      4007,
      'AMP Sehri Project (Hospitals)',
      'Mumbai',
      'Parel',
      NULL,
      'Near KEM, Tata Memorial, & Wadia Hospitals',
      'Central Mumbai',
      19.0031,
      72.8427,
      'NGO',
      'Free',
      '{"start":"03:00","end":"04:00"}'::jsonb,
      NULL,
      NULL,
      'Specifically for patients and relatives outside hospitals',
      ARRAY['Free','PatientSupport','Delivery']::text[],
      ARRAY['Hospital Patients','Patient Relatives']::text[],
      ARRAY['+917303116060']::text[],
      NULL
    ),
(
      4008,
      'Lucky Restaurant',
      'Mumbai',
      'Bandra West',
      NULL,
      'SV Road, Bandra West',
      'Suburbs',
      19.0514,
      72.8375,
      'Restaurant',
      'Paid',
      '{"start":"03:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','DineIn','BiryaniSpecial']::text[],
      NULL,
      ARRAY['022-26442973']::text[],
      NULL
    ),
(
      4009,
      'Bilali Masjid',
      'Mumbai',
      'Kurla East',
      NULL,
      'Qureshi Nagar, Kurla East',
      'Suburbs',
      19.0638,
      72.8794,
      'Masjid',
      'Free',
      '{"start":"03:30","end":"04:30"}'::jsonb,
      'Entire Ramadan',
      NULL,
      NULL,
      ARRAY['Free','DineIn','StudentFriendly']::text[],
      ARRAY['Students','Local Community']::text[],
      ARRAY['9324458770']::text[],
      NULL
    ),
(
      4010,
      'Persian Darbar',
      'Mumbai',
      'Jogeshwari West',
      NULL,
      'SV Road',
      'Suburbs',
      19.1417,
      72.8461,
      'Restaurant',
      'Paid',
      '{"start":"02:30","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      'Premium Raan Biryani for Sehri',
      ARRAY['Paid','DineIn','FamilyFriendly']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      4011,
      'Delhi Darbar',
      'Mumbai',
      'Colaba',
      NULL,
      'Colaba Causeway',
      'South Mumbai',
      18.9248,
      72.8322,
      'Restaurant',
      'Paid',
      '{"start":"03:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','DineIn','AC']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5001,
      'Makkah Masjid',
      'Hyderabad',
      'Charminar',
      NULL,
      'Near Charminar',
      'South',
      17.3605,
      78.4736,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:20"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn','LargeCapacity']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5002,
      'Hotel Shadab',
      'Hyderabad',
      'Charminar',
      NULL,
      'High Court Road, Ghansi Bazaar',
      'South',
      17.3668,
      78.4756,
      'Restaurant',
      'Paid',
      '{"start":"02:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      'Famous for Sehri Nihari and Paya',
      ARRAY['Paid','DineIn','AC']::text[],
      NULL,
      ARRAY['040-24565949']::text[],
      NULL
    ),
(
      5003,
      'Shah Ghouse Hotel & Restaurant',
      'Hyderabad',
      'Charminar',
      NULL,
      'Shah Ali Banda',
      'South',
      17.3569,
      78.4707,
      'Restaurant',
      'Paid',
      '{"start":"02:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','DineIn','FamilySection']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5004,
      'Masjid-e-Quba',
      'Hyderabad',
      'Mehdipatnam',
      NULL,
      NULL,
      'West',
      17.3949,
      78.441,
      'Masjid',
      'Free',
      '{"start":"03:15","end":"04:15"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5005,
      'Pista House',
      'Hyderabad',
      'Tolichowki',
      NULL,
      'Opposite Shaikpet Nala',
      'West',
      17.4086,
      78.4116,
      'Restaurant',
      'Paid',
      '{"start":"02:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      'Haleem available occasionally for Sehri',
      ARRAY['Paid','Takeaway','Delivery']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5006,
      'Masjid-e-Noor',
      'Hyderabad',
      'Tolichowki',
      NULL,
      'Paramount Colony',
      'West',
      17.4024,
      78.4112,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:15"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn','CommunityFunded']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5007,
      '4 Seasons Restaurant',
      'Hyderabad',
      'Tolichowki',
      NULL,
      NULL,
      'West',
      17.4056,
      78.4164,
      'Restaurant',
      'Paid',
      '{"start":"02:30","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','DineIn','MiddleEasternCuisine']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5008,
      'Masjid-e-Bilal',
      'Hyderabad',
      'AC Guards',
      NULL,
      NULL,
      'Central',
      17.3975,
      78.4552,
      'Masjid',
      'Free',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL
    ),
(
      5009,
      'Sohail Hotel',
      'Hyderabad',
      'Malakpet',
      NULL,
      'Nalgonda X Roads',
      'East',
      17.3768,
      78.4912,
      'Restaurant',
      'Paid',
      '{"start":"02:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      'Budget friendly sehri options',
      ARRAY['Paid','DineIn']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5010,
      'Masjid-e-Azizia',
      'Hyderabad',
      'Humayun Nagar',
      NULL,
      'Mehdipatnam Road',
      'West',
      17.3934,
      78.4485,
      'Masjid',
      'Free',
      '{"start":"03:00","end":"04:15"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Free','DineIn','TravelerSupport']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5011,
      'Grand Hotel',
      'Hyderabad',
      'Abids',
      NULL,
      'Abids Circle',
      'Central',
      17.3888,
      78.4764,
      'Restaurant',
      'Paid',
      '{"start":"01:30","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      'Open all night',
      ARRAY['Paid','DineIn','Historic']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5012,
      'Paramount Colony Gate 1 Distribution',
      'Hyderabad',
      'Tolichowki',
      NULL,
      NULL,
      'West',
      17.402,
      78.411,
      'Foundation',
      'Free',
      NULL,
      NULL,
      NULL,
      'Free Sehri food is often distributed here for those in need.',
      ARRAY['Free','Takeaway']::text[],
      NULL,
      NULL,
      NULL
    ),
(
      5013,
      'Nayab Hotel',
      'Hyderabad',
      'Charminar',
      NULL,
      'Nayapul Road',
      'South',
      17.3688,
      78.4789,
      'Restaurant',
      'Paid',
      '{"start":"03:00","end":"04:30"}'::jsonb,
      NULL,
      NULL,
      NULL,
      ARRAY['Paid','DineIn','BhejaFrySpecial']::text[],
      NULL,
      NULL,
      NULL
    );

-- 3. Reset the sequence to avoid ID conflicts with new submissions
-- Note: 'spots_location_id_seq' is the standard name created by identity columns
SELECT setval(pg_get_serial_sequence('public.spots', 'location_id'), MAX(location_id)) FROM public.spots;

COMMIT;
